### ISSUE TITLE
使用できない

### ISSUE THREAD

**Issue by xaiam** [kurozumi/EccubeMakerBundle#1]
```
-> % bin/console eccube:plugin:install --code EccubeMakerBundle
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FormPass" from namespace "Plugin\EccubeMakerBundle\DependencyInjection\Compiler".
Did you forget a "use" statement for e.g. "Symfony\Component\Form\DependencyInjection\FormPass" or "Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\FormPass"? in /Users/x/Projects/ec-cube-test/ec-cube/app/Plugin/EccubeMakerBundle-master/Resource/config/services_dev.php:5
Stack trace:
#0 /Users/x/Projects/ec-cube-test/ec-cube/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(41): include()
#1 /Users/x/Projects/ec-cube-test/ec-cube/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(44): Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader->Symfony\Component\DependencyInjection\Loader\{closure}('/Users/x/P...')
#2 /Users/x/Projects/ec-cube-test/ec-cube/vendor/symfony/config/Loader/FileLoader.php(153): Symfony\Component\DependencyInjection\Loader\PhpFileL in /Users/x/Projects/ec-cube-test/ec-cube/app/Plugin/EccubeMakerBundle-master/Resource/config/services_dev.php on line 5

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FormPass" from namespace "Plugin\EccubeMakerBundle\DependencyInjection\Compiler".
Did you forget a "use" statement for e.g. "Symfony\Component\Form\DependencyInjection\FormPass" or "Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\FormPass"? in /Users/x/Projects/ec-cube-test/ec-cube/app/Plugin/EccubeMakerBundle-master/Resource/config/services_dev.php:5
Stack trace:
#0 /Users/x/Projects/ec-cube-test/ec-cube/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(41): include()
#1 /Users/x/Projects/ec-cube-test/ec-cube/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(44): Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader->Symfony\Component\DependencyInjection\Loader\{closure}('/Users/x/P...')
#2 /Users/x/Projects/ec-cube-test/ec-cube/vendor/symfony/config/Loader/FileLoader.php(153): Symfony\Component\DependencyInjection\Loader\PhpFileL in /Users/x/Projects/ec-cube-test/ec-cube/app/Plugin/EccubeMakerBundle-master/Resource/config/services_dev.php on line 5
```

ダウンロードしたzipファイルを解凍しapp/Plugin/に移動させたがbin/consoleで上記のエラーが出る。何故ですか？

**Comment by kiyomizu** [comment]
ダウンロード後 Plugin に配置して 以下のコマンドが出力できれば動作する気がします。

```
$ bin/console list eccube:make 
  eccube:make:controller      Creates a new controller class
  eccube:make:entity          Creates or updates a Doctrine entity class, and optionally an API Platform resource
  eccube:make:form-extension  Creates a ec-cube form extension
  eccube:make:trait           Creates or updates a ec-cube entity trait
```

**Comment by kurozumi** [comment]
@xaiam 

プラグインのディレクトリ名が以下になっているからだと思います。
EccubeMakerBundle-master

以下のディレクトリ名に変更してください。
EccubeMakerBundle
